#RELACIONAMENTO ENTRE A TABELA DE TURMA COM A TABELA DE ALUNOS:
ALTER TABLE tbl_alunos ADD CONSTRAINT FK_TURMA
FOREIGN KEY(cod_turma)
REFERENCES tbl_turma (cod_turma);

#RELACIONAMENTO ENTRE A TABELA DE TURMA COM A TABELA DE DISCIPLINAS:
ALTER TABLE tbl_disciplina ADD CONSTRAINT FK_TURMA
FOREIGN KEY (cod_turma)
REFERENCES tbl_turma (cod_turma);